### ISSUE TITLE
Espresso IdlingResource example in kotlin and coroutine doesn't work

### ISSUE THREAD

**Issue by impvd** [android/testing-samples#356]
I am not sure if it is appropriate to cut this ticket, let me know if I was wrong.

I tried to create an example on the Idlingresoure with kotlin and coroutine, but got some error, I post the detail in [SO](https://stackoverflow.com/questions/65517701/espresso-idlingresource-example-in-kotlin-and-coroutine-doesnt-work), just wondering if anybody here would help to take a look at it?

**Comment by mrk-han** [comment]
Can close this issue. (User's question was answered in a comment on SO)

Issues in this repo are usually reserved for errors in the samples, or suggestions for improving the repo.

Please see: http://stackoverflow.com/questions/tagged/android-testing for questions.
