### ISSUE TITLE
Android JNI C++ Test

### ISSUE THREAD

**Issue by oncealong** [android/testing-samples#382]
How to test JNI C++ code？

What I do now:
1. write some C++ test code to call the `function` that I want to test
2. write some Jni to call `C++ test code`
3. write some Java test Code to call `Jni code`

but these test `C++ And Java test` code will remain in release apk.

Is there best pratice to test Jni C++ code ?

**Comment by utzcoz** [comment]
@oncealong What about tring [androidx.test.ext.junitgtest](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/test/ext/junit-gtest/src/main/java/androidx/test/ext/junitgtest/androidx-test-ext-junit-gtest-documentation.md)? It can be used to run C++ gtest code with Java/Kotlin JUnit runner on real device/Emulator.

**Comment by utzcoz** [comment]
cc @brettchabot , is it proper to add an example of androidx.test.ext.junitgtest in testing-sample?
