### ISSUE TITLE
how to find RecycleView

### ISSUE THREAD

**Issue by xiaoyuhao1995** [android/testing-samples#416]
RecycleView in fragment，But fragment in Activity。
its not work

![github](https://user-images.githubusercontent.com/39255279/143512200-66fa6071-cde5-4ed7-b723-dc4073edc737.png)

**Comment by mrk-han** [comment]
Can close this issue.

Issues in this repo are usually reserved for errors in the samples, or suggestions for improving the repo.

Please see: http://stackoverflow.com/questions/tagged/android-testing for questions.
