### ISSUE TITLE
how to launcher other App in AndroidJUnit4

### ISSUE THREAD

**Issue by wyj3531** [android/testing-samples#421]
@RunWith(AndroidJUnit4::class)
class ExampleInstrumentedTest {
    @Test
    fun useAppContext() {
        val pkgName = "com.qin.demo"
        val deviceContext = ApplicationProvider.getApplicationContext<Context>()
        val intent = deviceContext.packageManager.getLaunchIntentForPackage(pkgName)
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        deviceContext.startActivity(intent)
    }
}

**Comment by mrk-han** [comment]
To launch other apps, you will need to use uiautomator. androidjunit4 is just the runner.

Per the docs:

```
  // Launch the app
  val context = ApplicationProvider.getApplicationContext<Context>()
  val intent = context.packageManager.getLaunchIntentForPackage(
  BASIC_SAMPLE_PACKAGE).apply {
    // Clear out any previous instances
    addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK)
  }
  context.startActivity(intent)

  // Wait for the app to appear
  device.wait(
    Until.hasObject(By.pkg(BASIC_SAMPLE_PACKAGE).depth(0)),
    LAUNCH_TIMEOUT
    )
  }
}
```

https://developer.android.com/training/testing/other-components/ui-automator
