### ISSUE TITLE
Android - hide status and navigation bar completely for an app with nav drawer and app bar.

### ISSUE THREAD

**Issue by vimalcvs** [android/testing-samples#443]
How can I dynamically hide the status and the navigation bar completely?

The app contains a regular navigation drawer with a appbar / toolbar and FAB buttons.

When switching to full screen, the content of the navigation and the status bar is scrolled away. Two empty bars are left on the screen. I want those empty bars to hide.

   **if (Build.VERSION.SDK_INT <= 29)** 

![Alt desc](https://i.stack.imgur.com/UXAPz.png)

**Comment by utzcoz** [comment]
@vimalcvs What you need maybe be Android app's immersive mode: https://developer.android.com/training/system-ui/immersive.

**Comment by vimalcvs** [comment]
> 
It is working...... but not working in 30 lower version.

**Comment by utzcoz** [comment]
@vimalcvs It is not related to testing-samples. You can search how to implement immersive mode for app on older Android versions with Google.
