### ISSUE TITLE
No information about instrumentation was found in AndroidManifest.xml

### ISSUE THREAD

**Issue by JivinDotL** [android/testing-samples#444]
like this:
<instrumentation android:targetPackage="com.test.sample" android:name="android.test.InstrumentationTestRunner" />

adb shell am instrument -w -r -e class com.test.sample.ExampleInstrumentedTest#useAppContext com.test.sample/android.test.InstrumentationTestRunner
INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0

Can you share me a demo with instrumentation in AndroidManifest.xml? and can use 'adb shell am instrument -w -r -e class ....'

**Comment by JivinDotL** [comment]
.... .... in AndroidManifest.xml
    </application>

    <instrumentation
        android:name="ade.tec.runner"
        android:targetPackage="com.example.android.testing.androidjunitrunnersample"
        android:handleProfiling="false"
        android:functionalTest="false"
        android:label="Tests for Instrumentation."/>

</manifest>

**Comment by JivinDotL** [comment]
adb uninstall com.example.android.testing.androidjunitrunnersample.test
adb uninstall com.example.android.testing.androidjunitrunnersample
adb shell pm list instrumentation
adb install -r -t .\app\build\outputs\apk\debug\app-debug.apk
adb shell "am instrument -w com.example.android.testing.androidjunitrunnersample/ade.tec.runner"
INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0

**Comment by mrk-han** [comment]
Needs additional context / full STR is unclear.  Likely stale.

Recommend closing issue.
