### ISSUE TITLE
Not able to find the screenshots when run the testing-samples->ui->expresso->ScreenshotSample project

### ISSUE THREAD

**Issue by malav5076** [android/testing-samples#460]
When I run this ScreenshotJavaTest ,I am not able to find the screenshots taken. Not able to find in emulator and file manager

**Comment by olegosipenko** [comment]
ScreenshotSample uses Gradle managed device - it runs only during test execution. Gradle shuts it down after test execution, so you are not able to access it. But instead this sample uses TestStorageService, which allows saving of screenshots to your build folder. So, check the folder of the module where you run your tests: `build/outputs/managed_device_android_test_additional_output/flavors/NAME_OF_YOUR_FLAVOR/NAME_OF_YOUR_DEVICE`

**Comment by Sabir403** [comment]
Good action

**Comment by mrk-han** [comment]
Question answered per @olegosipenko 

Can close this issue.
